

# JOIN METHOD QUEREIS WITH DERIVER AND PASSENGER TABLES :-

CREATE DATABASE UBER;

USE UBER;

# TABLE - A

CREATE TABLE DRIVER
(
D_ID INT PRIMARY KEY,
F_NAME VARCHAR(25),
L_NAME VARCHAR(25),
P_NO VARCHAR(25),
AGE INT,
GENDER VARCHAR(15),
RATING DECIMAL(3,2)
 );
 
 # TABLE - B
 
CREATE TABLE PASSENGER
(
P_IDD INT PRIMARY KEY,
P_FNAME VARCHAR(20),
P_LNAME VARCHAR(20),
P_NO VARCHAR(15),
AGE INT,
GENDER VARCHAR(10),
RIDE_DATE DATE,
P_OTP INT,
FOREIGN KEY(P_OTP) REFERENCES DRIVER(D_ID)
);

# SHOW SAME RECORD FROM TABLE - A AND TABLE - B

SELECT*FROM DRIVER 
JOIN PASSENGER
ON DRIVER.D_ID = PASSENGER.P_OTP;

# SHOW ALL RECORD FROM TABLE - B AND SHOW MATCHING RECORD FROM TABLE A

SELECT*FROM DRIVER 
RIGHT JOIN PASSENGER
ON DRIVER.D_ID = PASSENGER.P_OTP;

# SHOW ALL RECORD FROM TABLE - A AND SHOW MATCHING RECORD FROM TABLE B

SELECT*FROM DRIVER 
LEFT JOIN PASSENGER
ON DRIVER.D_ID = PASSENGER.P_OTP;

# SHOE ALL RECORDS FROM BOTH TABLES

SELECT*FROM DRIVER
CROSS JOIN PASSENGER;

 


